version: "2"

services:
  jenkins:
    build: .
    depends_on:
      - dev_server
    links:
      - dev_server
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2202:22"
    volumes:
      - ./var/jenkins_home:/var/jenkins_home
      - ./root/.ssh/:/root/.ssh/
    environment:
      - ENVIRONMENT=docker
      - JENKINS_SLAVE_AGENT_PORT=50000
    networks:
      - back
    container_name: jenkins

  dev_server:
    build: ./docker/dev_server
    restart: always
    ports:
      - "8003:8000"
      - "2203:22"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENVIRONMENT=docker
    networks:
      - back

networks:
  back:
    driver: bridge
